### ISSUE TITLE
@index//:lock fails when yaml is in workspace root

### ISSUE THREAD

**Issue by NotBobTheBuilder** [GoogleContainerTools/rules_distroless#31]
Hello!

It appears the manifest for `deb_index` must be in a subdirectory for the `:lock` operation to complete successfully. If the manifest is at the workspace root, the `:lock` operation seems to try to write the lockfile into the os root directory `/`.

Here's an example minimum reproduction, and additional example of it working after moving the manifest

WORKSPACE.bazel
```
load("@rules_distroless//apt:index.bzl", "deb_index")

deb_index(
    name = "bullseye",
    # lock = "//:bullseye.lock.json",
    manifest = "//:bullseye.yaml",
)

load("@bullseye//:packages.bzl", "bullseye_packages")
bullseye_packages()
```

MODULE.bazel
```
bazel_dep(name = "rules_distroless", version = "0.3.1")
bazel_dep(name = "aspect_bazel_lib", version = "2.6.0")

bazel_lib_toolchains = use_extension("@aspect_bazel_lib//lib:extensions.bzl", "toolchains")
bazel_lib_toolchains.tar()
use_repo(bazel_lib_toolchains, "coreutils_toolchains")
use_repo(bazel_lib_toolchains, "yq_darwin_amd64")
use_repo(bazel_lib_toolchains, "yq_darwin_arm64")
use_repo(bazel_lib_toolchains, "yq_linux_amd64")
use_repo(bazel_lib_toolchains, "yq_linux_arm64")
use_repo(bazel_lib_toolchains, "yq_linux_ppc64le")
use_repo(bazel_lib_toolchains, "yq_linux_s390x")
use_repo(bazel_lib_toolchains, "yq_windows_amd64")
use_repo(bazel_lib_toolchains, "bsd_tar_toolchains")
```

bullseye.yaml
```
version: 1

sources:
  - channel: bullseye main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240411T144035Z
  - channel: bullseye-security main
    url: https://snapshot-cloudflare.debian.org/archive/debian-security/20240411T144035Z
  - channel: bullseye-updates main
    url: https://snapshot-cloudflare.debian.org/archive/debian/20240411T144035Z

archs:
  - "amd64"
  - "arm64"

packages:
  - "coreutils"
```

```
% bazel run @bullseye//:lock
DEBUG: /private/var/tmp/_bazel_jack/7705d353324d972c2f80e0a05b1568d6/external/rules_distroless~/apt/index.bzl:73:14: 
No lockfile was given, please run `bazel run @bullseye//:lock` to create the lockfile.
INFO: Analyzed target @@bullseye//:lock (85 packages loaded, 431 targets configured).
INFO: Found 1 target...
Target @@bullseye_resolution//:lock up-to-date:
  bazel-bin/external/bullseye_resolution/lock
INFO: Elapsed time: 0.334s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/external/bullseye_resolution/lock external/bullseye_resolution/lock.json

Writing lockfile to /bullseye.lock.json
cp: /bullseye.lock.json: Read-only file system
```

However upon making a directory `bullseye`, moving `bullseye.yaml` within it, creating an empty `BUILD` and rerunning:

```
% bazel run @bullseye//:lock
...
Writing lockfile to bullseye/bullseye.lock.json
```

I think this might be because when `locklabel.package` is empty, `workspace_relative_path` populates to `/{locklabel.name}` https://github.com/GoogleContainerTools/rules_distroless/blob/1447931b5ffa9efcdec1ce2e154115fd5805e3a8/apt/private/resolve.bzl#L113
